[package]
name = "hachi"
version = "0.1.0"
edition = "2021"

[dependencies]
notan = { git = "https://github.com/Nazariglez/notan", rev = "f74aabcba64eadadabb486ff1710863f546c2ef8", features = ["audio", "egui"] }
notan_extra = { git = "https://github.com/Nazariglez/notan", rev = "f74aabcba64eadadabb486ff1710863f546c2ef8" }
rfd = "0.15.0"
pollster = "0.4.0"
async-mutex = "1.4.0"
clap = { version = "4.5.21", features = ["derive"] }
serde = { version = "1.0.218", features = ["derive"] }
toml = "0.8.20"
dirs = "6.0.0"
